#!/bin/bash
chmod +x ./bin/VedaEMail
ln -s /lib/x86_64-linux-gnu/ld-2.27.so ./lib/ld-linux-x86-64.so.2
ln -s ./lib/libz.so.1.2.11 ./lib/ld-linux-x86-64.so.2
ln -s ./lib/libXrender.so.1.3.0 ./lib/libXrender.so.1
ln -s ./lib/libXdmcp.so.6.0.0 ./lib/libXdmcp.so.6
ln -s ./lib/libxcb-xkb.so.1.0.0 ./lib/libxcb-xkb.so.1
ln -s ./lib/libxcb-xinerama.so.0.0.0 ./lib/libxcb-xinerama.so.0
ln -s ./lib/libxcb-xfixes.so.0.0.0 ./lib/libxcb-xfixes.so.0
ln -s ./lib/libxcb-util.so.1.0.0 ./lib/libxcb-util.so.1
ln -s ./lib/libxcb-sync.so.1.0.0 ./lib/libxcb-sync.so.1
ln -s ./lib/libxcb.so.1.1.0 ./lib/libxcb.so.1
ln -s ./lib/libxcb-shm.so.0.0.0 ./lib/libxcb-shm.so.0
ln -s ./lib/libxcb-shape.so.0.0.0 ./lib/libxcb-shape.so.0
ln -s ./lib/libxcb-render-util.so.0.0.0 ./lib/libxcb-render-util.so.0
ln -s ./lib/libxcb-render.so.0.0.0 ./lib/libxcb-render.so.0
ln -s ./lib/libxcb-randr.so.0.1.0 ./lib/libxcb-randr.so.0
ln -s ./lib/libxcb-keysyms.so.1.0.0 ./lib/libxcb-keysyms.so.1
ln -s ./lib/libxcb-image.so.0.0.0 ./lib/libxcb-image.so.0
ln -s ./lib/libxcb-icccm.so.4.0.0 ./lib/libxcb-icccm.so.4
ln -s ./lib/libXau.so.6.0.0 ./lib/libXau.so.6
ln -s ./lib/libX11-xcb.so.1.0.0 ./lib/libX11-xcb.so.1
ln -s ./lib/libX11.so.6.3.0 ./lib/libX11.so.6
ln -s ./lib/libvedawallet.so.1.0.0 ./lib/libvedawallet.so
ln -s ./lib/libvedawallet.so.1.0.0 ./lib/libvedawallet.so.1
ln -s ./lib/libvedawallet.so.1.0.0 ./lib/libvedawallet.so.1.0
ln -s ./lib/libvedatransactions.so.1.0.0 ./lib/libvedatransactions.so
ln -s ./lib/libvedatransactions.so.1.0.0 ./lib/libvedatransactions.so.1
ln -s ./lib/libvedatransactions.so.1.0.0 ./lib/libvedatransactions.so.1.0
ln -s ./lib/libveda.so.1.0.0 ./lib/libveda.so
ln -s ./lib/libveda.so.1.0.0 ./lib/libveda.so.1
ln -s ./lib/libveda.so.1.0.0 ./lib/libveda.so.1.0
ln -s ./lib/libvedaserver.so.1.0.0 ./lib/libvedaserver.so
ln -s ./lib/libvedaserver.so.1.0.0 ./lib/libvedaserver.so.1
ln -s ./lib/libvedaserver.so.1.0.0 ./lib/libvedaserver.so.1.0
ln -s ./lib/libvedasat.so.1.0.0 ./lib/libvedasat.so
ln -s ./lib/libvedasat.so.1.0.0 ./lib/libvedasat.so.1
ln -s ./lib/libvedasat.so.1.0.0 ./lib/libvedasat.so.1.0
ln -s ./lib/libvedainiwrapper.so.1.0.0 ./lib/libvedainiwrapper.so
ln -s ./lib/libvedainiwrapper.so.1.0.0 ./lib/libvedainiwrapper.so.1
ln -s ./lib/libvedainiwrapper.so.1.0.0 ./lib/libvedainiwrapper.so.1.0
ln -s ./lib/libvedacrypto.so.1.0.0 ./lib/libvedacrypto.so
ln -s ./lib/libvedacrypto.so.1.0.0 ./lib/libvedacrypto.so.1
ln -s ./lib/libvedacrypto.so.1.0.0 ./lib/libvedacrypto.so.1.0
ln -s ./lib/libvedacryptobox.so.1.0.0 ./lib/libvedacryptobox.so
ln -s ./lib/libvedacryptobox.so.1.0.0 ./lib/libvedacryptobox.so.1
ln -s ./lib/libvedacryptobox.so.1.0.0 ./lib/libvedacryptobox.so.1.0
ln -s ./lib/libtiff.so.5.3.0 ./lib/libtiff.so.5
ln -s ./lib/libstdc++.so.6.0.25 ./lib/libstdc++.so.6
ln -s ./lib/libssl.so.1.1 ./lib/libssl.so
ln -s ./lib/libsqlite3.so.0.8.6 ./lib/libsqlite3.so
ln -s ./lib/libsqlite3.so.0.8.6 ./lib/libsqlite3.so.0
ln -s ./lib/librt-2.27.so ./lib/librt.so.1
ln -s ./lib/librocksdb.so.5.14.0 ./lib/librocksdb.so
ln -s ./lib/librocksdb.so.5.14.0 ./lib/librocksdb.so.5
ln -s ./lib/libpthread-2.27.so ./lib/libpthread.so.0
ln -s ./lib/libprotobuf.so.17.0.0 ./lib/libprotobuf.so
ln -s ./lib/libprotobuf.so.17.0.0 ./lib/libprotobuf.so.17
ln -s ./lib/libpng16.so.16.34.0 ./lib/libpng16.so.16
ln -s ./lib/libpcre.so.3.13.3 ./lib/libpcre.so.3
ln -s ./lib/libm-2.27.so ./lib/libm.so.6
ln -s ./lib/liblzma.so.5.2.2 ./lib/liblzma.so.5
ln -s ./lib/libjpeg.so.8.1.2 ./lib/libjpeg.so.8
ln -s ./lib/libicuuc.so.60.2 ./lib/libicuuc.so.60
ln -s ./lib/libicui18n.so.60.2 ./lib/libicui18n.so.60
ln -s ./lib/libicudata.so.60.2 ./lib/libicudata.so.60
ln -s ./lib/libharfbuzz.so.0.10702.0 ./lib/libharfbuzz.so.0
ln -s ./lib/libgraphite2.so.3.0.1 ./lib/libgraphite2.so.3
ln -s ./lib/libglib-2.0.so.0.5600.3 ./lib/libglib-2.0.so.0
ln -s ./lib/libfreetype.so.6.15.0 ./lib/libfreetype.so.6
ln -s ./lib/libfontconfig.so.1.10.1 ./lib/libfontconfig.so.1
ln -s ./lib/libexpat.so.1.6.7 ./lib/libexpat.so.1
ln -s ./lib/libdl-2.27.so ./lib/libdl.so.2
ln -s ./lib/libc-2.27.so ./lib/libc.so.6
ln -s ./lib/libcrypto.so.1.1 ./lib/libcrypto.so
ln -s ./lib/libbsd.so.0.8.7 ./lib/libbsd.so.0
LD_LIBRARY_PATH=$PWD/lib ./bin/VedaEMail
